name: Renovate

on:
  workflow_dispatch:
  # Run Renovate every night at 01:23 (24h time, randomly chosen).
  schedule:
    - cron: "23 01 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Renovate
        uses: https://github.com/renovatebot/github-action@v41.0.12
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_ENDPOINT: "https://codeberg.org/api/v1/"
          RENOVATE_PLATFORM: "gitea"
            
