// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APRemoteFollowOption a p remote follow option
//
// swagger:model APRemoteFollowOption
type APRemoteFollowOption struct {

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this a p remote follow option
func (m *APRemoteFollowOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this a p remote follow option based on context it is used
func (m *APRemoteFollowOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APRemoteFollowOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APRemoteFollowOption) UnmarshalBinary(b []byte) error {
	var res APRemoteFollowOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
