// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APPersonFollowItem a p person follow item
//
// swagger:model APPersonFollowItem
type APPersonFollowItem struct {

	// actor ID
	ActorID string `json:"actor_id,omitempty"`

	// note
	Note string `json:"note,omitempty"`

	// original item
	OriginalItem string `json:"original_item,omitempty"`

	// original URL
	OriginalURL string `json:"original_url,omitempty"`
}

// Validate validates this a p person follow item
func (m *APPersonFollowItem) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this a p person follow item based on context it is used
func (m *APPersonFollowItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APPersonFollowItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APPersonFollowItem) UnmarshalBinary(b []byte) error {
	var res APPersonFollowItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
