// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// ActionArtifact ActionArtifact represents an artifact of a workflow run
//
// swagger:model ActionArtifact
type ActionArtifact struct {

	// the URL to download the artifact zip archive
	ArchiveDownloadURL string `json:"archive_download_url,omitempty"`

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// whether the artifact has expired
	Expired bool `json:"expired,omitempty"`

	// expires at
	// Format: date-time
	ExpiresAt strfmt.DateTime `json:"expires_at,omitempty"`

	// the artifact's ID
	ID int64 `json:"id,omitempty"`

	// the artifact's name
	Name string `json:"name,omitempty"`

	// the ID of the workflow run that produced this artifact
	RunID int64 `json:"run_id,omitempty"`

	// the total size of the artifact in bytes
	SizeInBytes int64 `json:"size_in_bytes,omitempty"`

	// updated at
	// Format: date-time
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this action artifact
func (m *ActionArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExpiresAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ActionArtifact) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ActionArtifact) validateExpiresAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ExpiresAt) { // not required
		return nil
	}

	if err := validate.FormatOf("expires_at", "body", "date-time", m.ExpiresAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ActionArtifact) validateUpdatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.UpdatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.UpdatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this action artifact based on context it is used
func (m *ActionArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionArtifact) UnmarshalBinary(b []byte) error {
	var res ActionArtifact
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
