// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActionVariable ActionVariable return value of the query API
//
// swagger:model ActionVariable
type ActionVariable struct {

	// the value of the variable
	Data string `json:"data,omitempty"`

	// the name of the variable
	Name string `json:"name,omitempty"`

	// the owner to which the variable belongs
	OwnerID int64 `json:"owner_id,omitempty"`

	// the repository to which the variable belongs
	RepoID int64 `json:"repo_id,omitempty"`
}

// Validate validates this action variable
func (m *ActionVariable) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this action variable based on context it is used
func (m *ActionVariable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionVariable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionVariable) UnmarshalBinary(b []byte) error {
	var res ActionVariable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
