// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActionRunJob ActionRunJob represents a job of a run
//
// swagger:model ActionRunJob
type ActionRunJob struct {

	// the action run job id
	ID int64 `json:"id,omitempty"`

	// the action run job name
	Name string `json:"name,omitempty"`

	// the action run job needed ids
	Needs []string `json:"needs"`

	// the owner id
	OwnerID int64 `json:"owner_id,omitempty"`

	// the repository id
	RepoID int64 `json:"repo_id,omitempty"`

	// the action run job labels to run on
	RunsOn []string `json:"runs_on"`

	// the action run job status
	Status string `json:"status,omitempty"`

	// the action run job latest task id
	TaskID int64 `json:"task_id,omitempty"`
}

// Validate validates this action run job
func (m *ActionRunJob) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this action run job based on context it is used
func (m *ActionRunJob) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionRunJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionRunJob) UnmarshalBinary(b []byte) error {
	var res ActionRunJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
