// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// AnnotatedTag AnnotatedTag represents an annotated tag
//
// swagger:model AnnotatedTag
type AnnotatedTag struct {

	// message
	Message string `json:"message,omitempty"`

	// s h a
	SHA string `json:"sha,omitempty"`

	// tag
	Tag string `json:"tag,omitempty"`

	// URL
	URL string `json:"url,omitempty"`

	// archive download count
	ArchiveDownloadCount *TagArchiveDownloadCount `json:"archive_download_count,omitempty"`

	// object
	Object *AnnotatedTagObject `json:"object,omitempty"`

	// tagger
	Tagger *CommitUser `json:"tagger,omitempty"`

	// verification
	Verification *PayloadCommitVerification `json:"verification,omitempty"`
}

// Validate validates this annotated tag
func (m *AnnotatedTag) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArchiveDownloadCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObject(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTagger(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVerification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AnnotatedTag) validateArchiveDownloadCount(formats strfmt.Registry) error {
	if typeutils.IsZero(m.ArchiveDownloadCount) { // not required
		return nil
	}

	if m.ArchiveDownloadCount != nil {
		if err := m.ArchiveDownloadCount.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("archive_download_count")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("archive_download_count")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) validateObject(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Object) { // not required
		return nil
	}

	if m.Object != nil {
		if err := m.Object.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("object")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("object")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) validateTagger(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Tagger) { // not required
		return nil
	}

	if m.Tagger != nil {
		if err := m.Tagger.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tagger")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tagger")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) validateVerification(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Verification) { // not required
		return nil
	}

	if m.Verification != nil {
		if err := m.Verification.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("verification")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("verification")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this annotated tag based on the context it is used
func (m *AnnotatedTag) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateArchiveDownloadCount(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateObject(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTagger(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVerification(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AnnotatedTag) contextValidateArchiveDownloadCount(ctx context.Context, formats strfmt.Registry) error {

	if m.ArchiveDownloadCount != nil {

		if typeutils.IsZero(m.ArchiveDownloadCount) { // not required
			return nil
		}

		if err := m.ArchiveDownloadCount.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("archive_download_count")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("archive_download_count")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) contextValidateObject(ctx context.Context, formats strfmt.Registry) error {

	if m.Object != nil {

		if typeutils.IsZero(m.Object) { // not required
			return nil
		}

		if err := m.Object.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("object")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("object")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) contextValidateTagger(ctx context.Context, formats strfmt.Registry) error {

	if m.Tagger != nil {

		if typeutils.IsZero(m.Tagger) { // not required
			return nil
		}

		if err := m.Tagger.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("tagger")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("tagger")
			}

			return err
		}
	}

	return nil
}

func (m *AnnotatedTag) contextValidateVerification(ctx context.Context, formats strfmt.Registry) error {

	if m.Verification != nil {

		if typeutils.IsZero(m.Verification) { // not required
			return nil
		}

		if err := m.Verification.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("verification")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("verification")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AnnotatedTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AnnotatedTag) UnmarshalBinary(b []byte) error {
	var res AnnotatedTag
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
