// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APINotFound API not found
//
// swagger:model APINotFound
type APINotFound struct {

	// errors
	Errors []string `json:"errors"`

	// message
	Message string `json:"message,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this API not found
func (m *APINotFound) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API not found based on context it is used
func (m *APINotFound) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APINotFound) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APINotFound) UnmarshalBinary(b []byte) error {
	var res APINotFound
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
