// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIInternalServerError API internal server error
//
// swagger:model APIInternalServerError
type APIInternalServerError struct {

	// message
	Message string `json:"message,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this API internal server error
func (m *APIInternalServerError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API internal server error based on context it is used
func (m *APIInternalServerError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIInternalServerError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIInternalServerError) UnmarshalBinary(b []byte) error {
	var res APIInternalServerError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
