// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIInvalidTopicsError API invalid topics error
//
// swagger:model APIInvalidTopicsError
type APIInvalidTopicsError struct {

	// invalid topics
	InvalidTopics []string `json:"invalidTopics"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this API invalid topics error
func (m *APIInvalidTopicsError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API invalid topics error based on context it is used
func (m *APIInvalidTopicsError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIInvalidTopicsError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIInvalidTopicsError) UnmarshalBinary(b []byte) error {
	var res APIInvalidTopicsError
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
