// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// APIValidationError API validation error
//
// swagger:model APIValidationError
type APIValidationError struct {

	// message
	Message string `json:"message,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this API validation error
func (m *APIValidationError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API validation error based on context it is used
func (m *APIValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIValidationError) UnmarshalBinary(b []byte) error {
	var res APIValidationError
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
