// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIRepoArchivedError API repo archived error
//
// swagger:model APIRepoArchivedError
type APIRepoArchivedError struct {

	// message
	Message string `json:"message,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this API repo archived error
func (m *APIRepoArchivedError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API repo archived error based on context it is used
func (m *APIRepoArchivedError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRepoArchivedError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRepoArchivedError) UnmarshalBinary(b []byte) error {
	var res APIRepoArchivedError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
