// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIForbiddenError API forbidden error
//
// swagger:model APIForbiddenError
type APIForbiddenError struct {

	// message
	Message string `json:"message,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this API forbidden error
func (m *APIForbiddenError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this API forbidden error based on context it is used
func (m *APIForbiddenError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIForbiddenError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIForbiddenError) UnmarshalBinary(b []byte) error {
	var res APIForbiddenError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
