// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangedFile ChangedFile store information about files affected by the pull request
//
// swagger:model ChangedFile
type ChangedFile struct {

	// additions
	Additions int64 `json:"additions,omitempty"`

	// changes
	Changes int64 `json:"changes,omitempty"`

	// contents URL
	ContentsURL string `json:"contents_url,omitempty"`

	// deletions
	Deletions int64 `json:"deletions,omitempty"`

	// filename
	Filename string `json:"filename,omitempty"`

	// HTML URL
	HTMLURL string `json:"html_url,omitempty"`

	// previous filename
	PreviousFilename string `json:"previous_filename,omitempty"`

	// raw URL
	RawURL string `json:"raw_url,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

// Validate validates this changed file
func (m *ChangedFile) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this changed file based on context it is used
func (m *ChangedFile) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangedFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangedFile) UnmarshalBinary(b []byte) error {
	var res ChangedFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
