// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommitStats CommitStats is statistics for a RepoCommit
//
// swagger:model CommitStats
type CommitStats struct {

	// additions
	Additions int64 `json:"additions,omitempty"`

	// deletions
	Deletions int64 `json:"deletions,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this commit stats
func (m *CommitStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this commit stats based on context it is used
func (m *CommitStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommitStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommitStats) UnmarshalBinary(b []byte) error {
	var res CommitStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
