// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CommitStatusState CommitStatusState holds the state of a CommitStatus
// It can be "pending", "success", "error", "failure", "warning", or "skipped"
//
// swagger:model CommitStatusState
type CommitStatusState string

// Validate validates this commit status state
func (m CommitStatusState) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this commit status state based on context it is used
func (m CommitStatusState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
