// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateTagOption CreateTagOption options when creating a tag
//
// swagger:model CreateTagOption
type CreateTagOption struct {

	// message
	Message string `json:"message,omitempty"`

	// tag name
	// Required: true
	TagName *string `json:"tag_name"`

	// target
	Target string `json:"target,omitempty"`
}

// Validate validates this create tag option
func (m *CreateTagOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTagName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateTagOption) validateTagName(formats strfmt.Registry) error {

	if err := validate.Required("tag_name", "body", m.TagName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create tag option based on context it is used
func (m *CreateTagOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateTagOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateTagOption) UnmarshalBinary(b []byte) error {
	var res CreateTagOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
