// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreatePullReviewComment CreatePullReviewComment represent a review comment for creation api
//
// swagger:model CreatePullReviewComment
type CreatePullReviewComment struct {

	// body
	Body string `json:"body,omitempty"`

	// if comment to new file line or 0
	NewLineNum int64 `json:"new_position,omitempty"`

	// if comment to old file line or 0
	OldLineNum int64 `json:"old_position,omitempty"`

	// the tree path
	Path string `json:"path,omitempty"`
}

// Validate validates this create pull review comment
func (m *CreatePullReviewComment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create pull review comment based on context it is used
func (m *CreatePullReviewComment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreatePullReviewComment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePullReviewComment) UnmarshalBinary(b []byte) error {
	var res CreatePullReviewComment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
