// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// CreateQuotaRuleOptions CreateQuotaRuleOptions represents the options for creating a quota rule
//
// swagger:model CreateQuotaRuleOptions
type CreateQuotaRuleOptions struct {

	// The limit set by the rule
	Limit int64 `json:"limit,omitempty"`

	// Name of the rule to create
	Name string `json:"name,omitempty"`

	// The subjects affected by the rule
	Subjects []string `json:"subjects"`
}

// Validate validates this create quota rule options
func (m *CreateQuotaRuleOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create quota rule options based on context it is used
func (m *CreateQuotaRuleOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateQuotaRuleOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateQuotaRuleOptions) UnmarshalBinary(b []byte) error {
	var res CreateQuotaRuleOptions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
