// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateOrUpdateSecretOption CreateOrUpdateSecretOption defines the properties of the secret to create or update.
//
// swagger:model CreateOrUpdateSecretOption
type CreateOrUpdateSecretOption struct {

	// Data of the secret. Special characters will be retained. Line endings will be normalized to LF to match the
	// behaviour of browsers. Encode the data with Base64 if line endings should be retained.
	// Required: true
	Data *string `json:"data"`
}

// Validate validates this create or update secret option
func (m *CreateOrUpdateSecretOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateOrUpdateSecretOption) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create or update secret option based on context it is used
func (m *CreateOrUpdateSecretOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateOrUpdateSecretOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateOrUpdateSecretOption) UnmarshalBinary(b []byte) error {
	var res CreateOrUpdateSecretOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
