// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateOAuth2ApplicationOptions CreateOAuth2ApplicationOptions holds options to create an oauth2 application
//
// swagger:model CreateOAuth2ApplicationOptions
type CreateOAuth2ApplicationOptions struct {

	// confidential client
	ConfidentialClient bool `json:"confidential_client,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// redirect u r is
	RedirectURIs []string `json:"redirect_uris"`
}

// Validate validates this create o auth2 application options
func (m *CreateOAuth2ApplicationOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create o auth2 application options based on context it is used
func (m *CreateOAuth2ApplicationOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateOAuth2ApplicationOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateOAuth2ApplicationOptions) UnmarshalBinary(b []byte) error {
	var res CreateOAuth2ApplicationOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
