// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DismissPullReviewOptions DismissPullReviewOptions are options to dismiss a pull review
//
// swagger:model DismissPullReviewOptions
type DismissPullReviewOptions struct {

	// message
	Message string `json:"message,omitempty"`

	// priors
	Priors bool `json:"priors,omitempty"`
}

// Validate validates this dismiss pull review options
func (m *DismissPullReviewOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dismiss pull review options based on context it is used
func (m *DismissPullReviewOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DismissPullReviewOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DismissPullReviewOptions) UnmarshalBinary(b []byte) error {
	var res DismissPullReviewOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
