// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DispatchWorkflowRun DispatchWorkflowRun represents a workflow run
//
// swagger:model DispatchWorkflowRun
type DispatchWorkflowRun struct {

	// the workflow run id
	ID int64 `json:"id,omitempty"`

	// the jobs name
	Jobs []string `json:"jobs"`

	// a unique number for each run of a repository
	RunNumber int64 `json:"run_number,omitempty"`
}

// Validate validates this dispatch workflow run
func (m *DispatchWorkflowRun) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dispatch workflow run based on context it is used
func (m *DispatchWorkflowRun) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DispatchWorkflowRun) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DispatchWorkflowRun) UnmarshalBinary(b []byte) error {
	var res DispatchWorkflowRun
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
