// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// EditLabelOption EditLabelOption options for editing a label
//
// swagger:model EditLabelOption
type EditLabelOption struct {

	// color
	// Example: #00aabb
	Color string `json:"color,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// exclusive
	// Example: false
	Exclusive bool `json:"exclusive,omitempty"`

	// is archived
	// Example: false
	IsArchived bool `json:"is_archived,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this edit label option
func (m *EditLabelOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edit label option based on context it is used
func (m *EditLabelOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditLabelOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditLabelOption) UnmarshalBinary(b []byte) error {
	var res EditLabelOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
