// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// EditQuotaRuleOptions EditQuotaRuleOptions represents the options for editing a quota rule
//
// swagger:model EditQuotaRuleOptions
type EditQuotaRuleOptions struct {

	// The limit set by the rule
	Limit int64 `json:"limit,omitempty"`

	// The subjects affected by the rule
	Subjects []string `json:"subjects"`
}

// Validate validates this edit quota rule options
func (m *EditQuotaRuleOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edit quota rule options based on context it is used
func (m *EditQuotaRuleOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditQuotaRuleOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditQuotaRuleOptions) UnmarshalBinary(b []byte) error {
	var res EditQuotaRuleOptions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
