// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// EditHookOption EditHookOption options when modify one hook
//
// swagger:model EditHookOption
type EditHookOption struct {

	// active
	Active bool `json:"active,omitempty"`

	// authorization header
	AuthorizationHeader string `json:"authorization_header,omitempty"`

	// branch filter
	BranchFilter string `json:"branch_filter,omitempty"`

	// config
	Config map[string]string `json:"config,omitempty"`

	// events
	Events []string `json:"events"`
}

// Validate validates this edit hook option
func (m *EditHookOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edit hook option based on context it is used
func (m *EditHookOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditHookOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditHookOption) UnmarshalBinary(b []byte) error {
	var res EditHookOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
