// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EditReactionOption EditReactionOption contain the reaction type
//
// swagger:model EditReactionOption
type EditReactionOption struct {

	// reaction
	Reaction string `json:"content,omitempty"`
}

// Validate validates this edit reaction option
func (m *EditReactionOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this edit reaction option based on context it is used
func (m *EditReactionOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditReactionOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditReactionOption) UnmarshalBinary(b []byte) error {
	var res EditReactionOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
