// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ExternalWiki ExternalWiki represents setting for external wiki
//
// swagger:model ExternalWiki
type ExternalWiki struct {

	// URL of external wiki.
	ExternalWikiURL string `json:"external_wiki_url,omitempty"`
}

// Validate validates this external wiki
func (m *ExternalWiki) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this external wiki based on context it is used
func (m *ExternalWiki) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalWiki) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalWiki) UnmarshalBinary(b []byte) error {
	var res ExternalWiki
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
