// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GeneralUISettings GeneralUISettings contains global ui settings exposed by API
//
// swagger:model GeneralUISettings
type GeneralUISettings struct {

	// allowed reactions
	AllowedReactions []string `json:"allowed_reactions"`

	// custom emojis
	CustomEmojis []string `json:"custom_emojis"`

	// default theme
	DefaultTheme string `json:"default_theme,omitempty"`
}

// Validate validates this general UI settings
func (m *GeneralUISettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this general UI settings based on context it is used
func (m *GeneralUISettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeneralUISettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeneralUISettings) UnmarshalBinary(b []byte) error {
	var res GeneralUISettings
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
