// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GeneralRepoSettings GeneralRepoSettings contains global repository settings exposed by API
//
// swagger:model GeneralRepoSettings
type GeneralRepoSettings struct {

	// forks disabled
	ForksDisabled bool `json:"forks_disabled,omitempty"`

	// HTTP git disabled
	HTTPGitDisabled bool `json:"http_git_disabled,omitempty"`

	// l f s disabled
	LFSDisabled bool `json:"lfs_disabled,omitempty"`

	// migrations disabled
	MigrationsDisabled bool `json:"migrations_disabled,omitempty"`

	// mirrors disabled
	MirrorsDisabled bool `json:"mirrors_disabled,omitempty"`

	// stars disabled
	StarsDisabled bool `json:"stars_disabled,omitempty"`

	// time tracking disabled
	TimeTrackingDisabled bool `json:"time_tracking_disabled,omitempty"`
}

// Validate validates this general repo settings
func (m *GeneralRepoSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this general repo settings based on context it is used
func (m *GeneralRepoSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeneralRepoSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeneralRepoSettings) UnmarshalBinary(b []byte) error {
	var res GeneralRepoSettings
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
