// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GeneralAPISettings GeneralAPISettings contains global api settings exposed by it
//
// swagger:model GeneralAPISettings
type GeneralAPISettings struct {

	// default git trees per page
	DefaultGitTreesPerPage int64 `json:"default_git_trees_per_page,omitempty"`

	// default max blob size
	DefaultMaxBlobSize int64 `json:"default_max_blob_size,omitempty"`

	// default paging num
	DefaultPagingNum int64 `json:"default_paging_num,omitempty"`

	// max response items
	MaxResponseItems int64 `json:"max_response_items,omitempty"`
}

// Validate validates this general API settings
func (m *GeneralAPISettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this general API settings based on context it is used
func (m *GeneralAPISettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GeneralAPISettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GeneralAPISettings) UnmarshalBinary(b []byte) error {
	var res GeneralAPISettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
