// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// GitObject GitObject represents a Git object.
//
// swagger:model GitObject
type GitObject struct {

	// s h a
	SHA string `json:"sha,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this git object
func (m *GitObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this git object based on context it is used
func (m *GitObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GitObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GitObject) UnmarshalBinary(b []byte) error {
	var res GitObject
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
