// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// Hook Hook a hook is a web hook when one repository changed
//
// swagger:model Hook
type Hook struct {

	// active
	Active bool `json:"active,omitempty"`

	// authorization header
	AuthorizationHeader string `json:"authorization_header,omitempty"`

	// branch filter
	BranchFilter string `json:"branch_filter,omitempty"`

	// Deprecated: use Metadata instead
	Config map[string]string `json:"config,omitempty"`

	// content type
	ContentType string `json:"content_type,omitempty"`

	// created
	// Format: date-time
	Created strfmt.DateTime `json:"created_at,omitempty"`

	// events
	Events []string `json:"events"`

	// ID
	ID int64 `json:"id,omitempty"`

	// metadata
	Metadata any `json:"metadata,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// URL
	URL string `json:"url,omitempty"`

	// updated
	// Format: date-time
	Updated strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this hook
func (m *Hook) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Hook) validateCreated(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *Hook) validateUpdated(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Updated) { // not required
		return nil
	}

	if err := validate.FormatOf("updated_at", "body", "date-time", m.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this hook based on context it is used
func (m *Hook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Hook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Hook) UnmarshalBinary(b []byte) error {
	var res Hook
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
