// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IssueFormFieldType IssueFormFieldType defines issue form field type, can be "markdown", "textarea", "input", "dropdown" or "checkboxes"
//
// swagger:model IssueFormFieldType
type IssueFormFieldType string

// Validate validates this issue form field type
func (m IssueFormFieldType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this issue form field type based on context it is used
func (m IssueFormFieldType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
