// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IssueTemplateLabels issue template labels
//
// swagger:model IssueTemplateLabels
type IssueTemplateLabels []string

// Validate validates this issue template labels
func (m IssueTemplateLabels) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this issue template labels based on context it is used
func (m IssueTemplateLabels) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
