// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// IssueMeta IssueMeta basic issue information
//
// swagger:model IssueMeta
type IssueMeta struct {

	// index
	Index int64 `json:"index,omitempty"`

	// name
	Name string `json:"repo,omitempty"`

	// owner
	Owner string `json:"owner,omitempty"`
}

// Validate validates this issue meta
func (m *IssueMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this issue meta based on context it is used
func (m *IssueMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IssueMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IssueMeta) UnmarshalBinary(b []byte) error {
	var res IssueMeta
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
