// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IssueFormFieldVisible IssueFormFieldVisible defines issue form field visible
//
// swagger:model IssueFormFieldVisible
type IssueFormFieldVisible string

// Validate validates this issue form field visible
func (m IssueFormFieldVisible) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this issue form field visible based on context it is used
func (m IssueFormFieldVisible) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
