// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LabelTemplate LabelTemplate info of a Label template
//
// swagger:model LabelTemplate
type LabelTemplate struct {

	// color
	// Example: 00aabb
	Color string `json:"color,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// exclusive
	// Example: false
	Exclusive bool `json:"exclusive,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this label template
func (m *LabelTemplate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this label template based on context it is used
func (m *LabelTemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LabelTemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LabelTemplate) UnmarshalBinary(b []byte) error {
	var res LabelTemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
