// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// LicensesTemplateListEntry LicensesListEntry is used for the API
//
// swagger:model LicensesTemplateListEntry
type LicensesTemplateListEntry struct {

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this licenses template list entry
func (m *LicensesTemplateListEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this licenses template list entry based on context it is used
func (m *LicensesTemplateListEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicensesTemplateListEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicensesTemplateListEntry) UnmarshalBinary(b []byte) error {
	var res LicensesTemplateListEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
