// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// LicenseTemplateInfo LicensesInfo contains information about a License
//
// swagger:model LicenseTemplateInfo
type LicenseTemplateInfo struct {

	// body
	Body string `json:"body,omitempty"`

	// implementation
	Implementation string `json:"implementation,omitempty"`

	// key
	Key string `json:"key,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this license template info
func (m *LicenseTemplateInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this license template info based on context it is used
func (m *LicenseTemplateInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LicenseTemplateInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LicenseTemplateInfo) UnmarshalBinary(b []byte) error {
	var res LicenseTemplateInfo
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
