// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// MarkdownOption MarkdownOption markdown options
//
// swagger:model MarkdownOption
type MarkdownOption struct {

	// Context to render
	Context string `json:"Context,omitempty"`

	// Mode to render (comment, gfm, markdown)
	Mode string `json:"Mode,omitempty"`

	// Text markdown to render
	Text string `json:"Text,omitempty"`

	// Is it a wiki page ?
	Wiki bool `json:"Wiki,omitempty"`
}

// Validate validates this markdown option
func (m *MarkdownOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this markdown option based on context it is used
func (m *MarkdownOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarkdownOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarkdownOption) UnmarshalBinary(b []byte) error {
	var res MarkdownOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
