// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarkupOption MarkupOption markup options
//
// swagger:model MarkupOption
type MarkupOption struct {

	// The current branch path where the form gets posted
	//
	// in: body
	BranchPath string `json:"BranchPath,omitempty"`

	// Context to render
	//
	// in: body
	Context string `json:"Context,omitempty"`

	// File path for detecting extension in file mode
	//
	// in: body
	FilePath string `json:"FilePath,omitempty"`

	// Mode to render (comment, gfm, markdown, file)
	//
	// in: body
	Mode string `json:"Mode,omitempty"`

	// Text markup to render
	//
	// in: body
	Text string `json:"Text,omitempty"`

	// Is it a wiki page ?
	//
	// in: body
	Wiki bool `json:"Wiki,omitempty"`
}

// Validate validates this markup option
func (m *MarkupOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this markup option based on context it is used
func (m *MarkupOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarkupOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarkupOption) UnmarshalBinary(b []byte) error {
	var res MarkupOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
