// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIssuePinsAllowed NewIssuePinsAllowed represents an API response that says if new Issue Pins are allowed
//
// swagger:model NewIssuePinsAllowed
type NewIssuePinsAllowed struct {

	// issues
	Issues bool `json:"issues,omitempty"`

	// pull requests
	PullRequests bool `json:"pull_requests,omitempty"`
}

// Validate validates this new issue pins allowed
func (m *NewIssuePinsAllowed) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this new issue pins allowed based on context it is used
func (m *NewIssuePinsAllowed) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NewIssuePinsAllowed) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NewIssuePinsAllowed) UnmarshalBinary(b []byte) error {
	var res NewIssuePinsAllowed
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
