// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
)

// NodeInfoUsage NodeInfoUsage contains usage statistics for this server
//
// swagger:model NodeInfoUsage
type NodeInfoUsage struct {

	// local comments
	LocalComments int64 `json:"localComments,omitempty"`

	// local posts
	LocalPosts int64 `json:"localPosts,omitempty"`

	// users
	Users *NodeInfoUsageUsers `json:"users,omitempty"`
}

// Validate validates this node info usage
func (m *NodeInfoUsage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateUsers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NodeInfoUsage) validateUsers(formats strfmt.Registry) error {
	if typeutils.IsZero(m.Users) { // not required
		return nil
	}

	if m.Users != nil {
		if err := m.Users.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("users")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("users")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this node info usage based on the context it is used
func (m *NodeInfoUsage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUsers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *NodeInfoUsage) contextValidateUsers(ctx context.Context, formats strfmt.Registry) error {

	if m.Users != nil {

		if typeutils.IsZero(m.Users) { // not required
			return nil
		}

		if err := m.Users.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("users")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("users")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *NodeInfoUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeInfoUsage) UnmarshalBinary(b []byte) error {
	var res NodeInfoUsage
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
