// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NodeInfoUsageUsers NodeInfoUsageUsers contains statistics about the users of this server
//
// swagger:model NodeInfoUsageUsers
type NodeInfoUsageUsers struct {

	// active halfyear
	ActiveHalfyear int64 `json:"activeHalfyear,omitempty"`

	// active month
	ActiveMonth int64 `json:"activeMonth,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this node info usage users
func (m *NodeInfoUsageUsers) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this node info usage users based on context it is used
func (m *NodeInfoUsageUsers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NodeInfoUsageUsers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NodeInfoUsageUsers) UnmarshalBinary(b []byte) error {
	var res NodeInfoUsageUsers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
