// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NoteOptions note options
//
// swagger:model NoteOptions
type NoteOptions struct {

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this note options
func (m *NoteOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this note options based on context it is used
func (m *NoteOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NoteOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NoteOptions) UnmarshalBinary(b []byte) error {
	var res NoteOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
