// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NotificationCount NotificationCount number of unread notifications
//
// swagger:model NotificationCount
type NotificationCount struct {

	// new
	New int64 `json:"new,omitempty"`
}

// Validate validates this notification count
func (m *NotificationCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this notification count based on context it is used
func (m *NotificationCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NotificationCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NotificationCount) UnmarshalBinary(b []byte) error {
	var res NotificationCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
