// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// PullReviewRequestOptions PullReviewRequestOptions are options to add or remove pull review requests
//
// swagger:model PullReviewRequestOptions
type PullReviewRequestOptions struct {

	// reviewers
	Reviewers []string `json:"reviewers"`

	// team reviewers
	TeamReviewers []string `json:"team_reviewers"`
}

// Validate validates this pull review request options
func (m *PullReviewRequestOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pull review request options based on context it is used
func (m *PullReviewRequestOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PullReviewRequestOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PullReviewRequestOptions) UnmarshalBinary(b []byte) error {
	var res PullReviewRequestOptions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
