// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// QuotaUsedSizeAssetsAttachments QuotaUsedSizeAssetsAttachments represents the size-based attachment quota usage of a user
//
// swagger:model QuotaUsedSizeAssetsAttachments
type QuotaUsedSizeAssetsAttachments struct {

	// Storage size used for the user's issue & comment attachments
	Issues int64 `json:"issues,omitempty"`

	// Storage size used for the user's release attachments
	Releases int64 `json:"releases,omitempty"`
}

// Validate validates this quota used size assets attachments
func (m *QuotaUsedSizeAssetsAttachments) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quota used size assets attachments based on context it is used
func (m *QuotaUsedSizeAssetsAttachments) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuotaUsedSizeAssetsAttachments) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuotaUsedSizeAssetsAttachments) UnmarshalBinary(b []byte) error {
	var res QuotaUsedSizeAssetsAttachments
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
