// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// QuotaUsedSizeAssetsPackages QuotaUsedSizeAssetsPackages represents the size-based package quota usage of a user
//
// swagger:model QuotaUsedSizeAssetsPackages
type QuotaUsedSizeAssetsPackages struct {

	// Storage suze used for the user's packages
	All int64 `json:"all,omitempty"`
}

// Validate validates this quota used size assets packages
func (m *QuotaUsedSizeAssetsPackages) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quota used size assets packages based on context it is used
func (m *QuotaUsedSizeAssetsPackages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuotaUsedSizeAssetsPackages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuotaUsedSizeAssetsPackages) UnmarshalBinary(b []byte) error {
	var res QuotaUsedSizeAssetsPackages
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
