// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// QuotaUsedArtifact QuotaUsedArtifact represents an artifact counting towards a user's quota
//
// swagger:model QuotaUsedArtifact
type QuotaUsedArtifact struct {

	// HTML URL to the action run containing the artifact
	HTMLURL string `json:"html_url,omitempty"`

	// Name of the artifact
	Name string `json:"name,omitempty"`

	// Size of the artifact (compressed)
	Size int64 `json:"size,omitempty"`
}

// Validate validates this quota used artifact
func (m *QuotaUsedArtifact) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this quota used artifact based on context it is used
func (m *QuotaUsedArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *QuotaUsedArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *QuotaUsedArtifact) UnmarshalBinary(b []byte) error {
	var res QuotaUsedArtifact
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
