// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// RegisterRunnerOptions RegisterRunnerOptions declares the accepted options for registering runners.
//
// swagger:model RegisterRunnerOptions
type RegisterRunnerOptions struct {

	// Description of the runner to register.
	Description string `json:"description,omitempty"`

	// Register as ephemeral runner https://forgejo.org/docs/latest/admin/actions/security/#ephemeral-runner
	Ephemeral bool `json:"ephemeral,omitempty"`

	// Name of the runner to register. The name of the runner does not have to be unique.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this register runner options
func (m *RegisterRunnerOptions) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterRunnerOptions) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register runner options based on context it is used
func (m *RegisterRunnerOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterRunnerOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterRunnerOptions) UnmarshalBinary(b []byte) error {
	var res RegisterRunnerOptions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
