// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RegistrationToken RegistrationToken is a string used to register a runner with a server
//
// swagger:model RegistrationToken
type RegistrationToken struct {

	// token
	Token string `json:"token,omitempty"`
}

// Validate validates this registration token
func (m *RegistrationToken) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this registration token based on context it is used
func (m *RegistrationToken) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegistrationToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegistrationToken) UnmarshalBinary(b []byte) error {
	var res RegistrationToken
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
