// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RenameOrgOption RenameOrgOption options when renaming an organization
//
// swagger:model RenameOrgOption
type RenameOrgOption struct {

	// New username for this org. This name cannot be in use yet by any other user.
	// Required: true
	NewName *string `json:"new_name"`
}

// Validate validates this rename org option
func (m *RenameOrgOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RenameOrgOption) validateNewName(formats strfmt.Registry) error {

	if err := validate.Required("new_name", "body", m.NewName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this rename org option based on context it is used
func (m *RenameOrgOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RenameOrgOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RenameOrgOption) UnmarshalBinary(b []byte) error {
	var res RenameOrgOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
