// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RenameUserOption RenameUserOption options when renaming a user
//
// swagger:model RenameUserOption
type RenameUserOption struct {

	// New username for this user. This name cannot be in use yet by any other user.
	// Required: true
	NewName *string `json:"new_username"`
}

// Validate validates this rename user option
func (m *RenameUserOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RenameUserOption) validateNewName(formats strfmt.Registry) error {

	if err := validate.Required("new_username", "body", m.NewName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this rename user option based on context it is used
func (m *RenameUserOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RenameUserOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RenameUserOption) UnmarshalBinary(b []byte) error {
	var res RenameUserOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
