// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ReplaceFlagsOption ReplaceFlagsOption options when replacing the flags of a repository
//
// swagger:model ReplaceFlagsOption
type ReplaceFlagsOption struct {

	// flags
	Flags []string `json:"flags"`
}

// Validate validates this replace flags option
func (m *ReplaceFlagsOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this replace flags option based on context it is used
func (m *ReplaceFlagsOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReplaceFlagsOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReplaceFlagsOption) UnmarshalBinary(b []byte) error {
	var res ReplaceFlagsOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
