// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// RepoTopicOptions RepoTopicOptions a collection of repo topic names
//
// swagger:model RepoTopicOptions
type RepoTopicOptions struct {

	// list of topic names
	Topics []string `json:"topics"`
}

// Validate validates this repo topic options
func (m *RepoTopicOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this repo topic options based on context it is used
func (m *RepoTopicOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepoTopicOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepoTopicOptions) UnmarshalBinary(b []byte) error {
	var res RepoTopicOptions
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
