// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ReviewStateType ReviewStateType review state type
//
// swagger:model ReviewStateType
type ReviewStateType string

// Validate validates this review state type
func (m ReviewStateType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this review state type based on context it is used
func (m ReviewStateType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
