// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// ServerVersion ServerVersion wraps the version of the server
//
// swagger:model ServerVersion
type ServerVersion struct {

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this server version
func (m *ServerVersion) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this server version based on context it is used
func (m *ServerVersion) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServerVersion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServerVersion) UnmarshalBinary(b []byte) error {
	var res ServerVersion
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
