// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// StateType StateType issue state type
//
// swagger:model StateType
type StateType string

// Validate validates this state type
func (m StateType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this state type based on context it is used
func (m StateType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
