// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// SyncForkInfo SyncForkInfo information about syncing a fork
//
// swagger:model SyncForkInfo
type SyncForkInfo struct {

	// allowed
	Allowed bool `json:"allowed,omitempty"`

	// base commit
	BaseCommit string `json:"base_commit,omitempty"`

	// commits behind
	CommitsBehind int64 `json:"commits_behind,omitempty"`

	// fork commit
	ForkCommit string `json:"fork_commit,omitempty"`
}

// Validate validates this sync fork info
func (m *SyncForkInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sync fork info based on context it is used
func (m *SyncForkInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SyncForkInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyncForkInfo) UnmarshalBinary(b []byte) error {
	var res SyncForkInfo
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
