// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TagArchiveDownloadCount TagArchiveDownloadCount counts how many times a archive was downloaded
//
// swagger:model TagArchiveDownloadCount
type TagArchiveDownloadCount struct {

	// tar gz
	TarGz int64 `json:"tar_gz,omitempty"`

	// zip
	Zip int64 `json:"zip,omitempty"`
}

// Validate validates this tag archive download count
func (m *TagArchiveDownloadCount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tag archive download count based on context it is used
func (m *TagArchiveDownloadCount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TagArchiveDownloadCount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TagArchiveDownloadCount) UnmarshalBinary(b []byte) error {
	var res TagArchiveDownloadCount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
