// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TimeStamp TimeStamp defines a timestamp
//
// swagger:model TimeStamp
type TimeStamp int64

// Validate validates this time stamp
func (m TimeStamp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this time stamp based on context it is used
func (m TimeStamp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
