// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// TopicName TopicName a list of repo topic names
//
// swagger:model TopicName
type TopicName struct {

	// topic names
	TopicNames []string `json:"topics"`
}

// Validate validates this topic name
func (m *TopicName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this topic name based on context it is used
func (m *TopicName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TopicName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TopicName) UnmarshalBinary(b []byte) error {
	var res TopicName
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
