// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TransferRepoOption TransferRepoOption options when transfer a repository's ownership
//
// swagger:model TransferRepoOption
type TransferRepoOption struct {

	// new owner
	// Required: true
	NewOwner *string `json:"new_owner"`

	// ID of the team or teams to add to the repository. Teams can only be added to organization-owned repositories.
	TeamIDs []int64 `json:"team_ids"`
}

// Validate validates this transfer repo option
func (m *TransferRepoOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNewOwner(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TransferRepoOption) validateNewOwner(formats strfmt.Registry) error {

	if err := validate.Required("new_owner", "body", m.NewOwner); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this transfer repo option based on context it is used
func (m *TransferRepoOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransferRepoOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransferRepoOption) UnmarshalBinary(b []byte) error {
	var res TransferRepoOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
