// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRepoAvatarOption UpdateRepoAvatarUserOption options when updating the repo avatar
//
// swagger:model UpdateRepoAvatarOption
type UpdateRepoAvatarOption struct {

	// image must be base64 encoded
	Image string `json:"image,omitempty"`
}

// Validate validates this update repo avatar option
func (m *UpdateRepoAvatarOption) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update repo avatar option based on context it is used
func (m *UpdateRepoAvatarOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRepoAvatarOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRepoAvatarOption) UnmarshalBinary(b []byte) error {
	var res UpdateRepoAvatarOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
