// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
)

// UserSettings UserSettings represents user settings
//
// swagger:model UserSettings
type UserSettings struct {

	// description
	Description string `json:"description,omitempty"`

	// diff view style
	DiffViewStyle string `json:"diff_view_style,omitempty"`

	// enable repo unit hints
	EnableRepoUnitHints bool `json:"enable_repo_unit_hints,omitempty"`

	// full name
	FullName string `json:"full_name,omitempty"`

	// hide activity
	HideActivity bool `json:"hide_activity,omitempty"`

	// Privacy
	HideEmail bool `json:"hide_email,omitempty"`

	// hide pronouns
	HidePronouns bool `json:"hide_pronouns,omitempty"`

	// language
	Language string `json:"language,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// pronouns
	Pronouns string `json:"pronouns,omitempty"`

	// theme
	Theme string `json:"theme,omitempty"`

	// website
	Website string `json:"website,omitempty"`
}

// Validate validates this user settings
func (m *UserSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user settings based on context it is used
func (m *UserSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserSettings) UnmarshalBinary(b []byte) error {
	var res UserSettings
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
