// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/validate"
)

// VerifyGPGKeyOption VerifyGPGKeyOption options verifies user GPG key
//
// swagger:model VerifyGPGKeyOption
type VerifyGPGKeyOption struct {

	// An Signature for a GPG key token
	// Required: true
	KeyID *string `json:"key_id"`

	// signature
	Signature string `json:"armored_signature,omitempty"`
}

// Validate validates this verify g p g key option
func (m *VerifyGPGKeyOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKeyID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VerifyGPGKeyOption) validateKeyID(formats strfmt.Registry) error {

	if err := validate.Required("key_id", "body", m.KeyID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this verify g p g key option based on context it is used
func (m *VerifyGPGKeyOption) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifyGPGKeyOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifyGPGKeyOption) UnmarshalBinary(b []byte) error {
	var res VerifyGPGKeyOption
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
