// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// WatchInfo WatchInfo represents an API watch status of one repository
//
// swagger:model WatchInfo
type WatchInfo struct {

	// created at
	// Format: date-time
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// ignored
	Ignored bool `json:"ignored,omitempty"`

	// reason
	Reason any `json:"reason,omitempty"`

	// repository URL
	RepositoryURL string `json:"repository_url,omitempty"`

	// subscribed
	Subscribed bool `json:"subscribed,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this watch info
func (m *WatchInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WatchInfo) validateCreatedAt(formats strfmt.Registry) error {
	if typeutils.IsZero(m.CreatedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this watch info based on context it is used
func (m *WatchInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WatchInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WatchInfo) UnmarshalBinary(b []byte) error {
	var res WatchInfo
	if err := jsonutils.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
