// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WikiCommitList WikiCommitList commit/revision list
//
// swagger:model WikiCommitList
type WikiCommitList struct {

	// count
	Count int64 `json:"count,omitempty"`

	// wiki commits
	WikiCommits []*WikiCommit `json:"commits"`
}

// Validate validates this wiki commit list
func (m *WikiCommitList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWikiCommits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiCommitList) validateWikiCommits(formats strfmt.Registry) error {
	if swag.IsZero(m.WikiCommits) { // not required
		return nil
	}

	for i := 0; i < len(m.WikiCommits); i++ {
		if swag.IsZero(m.WikiCommits[i]) { // not required
			continue
		}

		if m.WikiCommits[i] != nil {
			if err := m.WikiCommits[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("commits" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("commits" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this wiki commit list based on the context it is used
func (m *WikiCommitList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWikiCommits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiCommitList) contextValidateWikiCommits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.WikiCommits); i++ {

		if m.WikiCommits[i] != nil {

			if swag.IsZero(m.WikiCommits[i]) { // not required
				return nil
			}

			if err := m.WikiCommits[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("commits" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("commits" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *WikiCommitList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WikiCommitList) UnmarshalBinary(b []byte) error {
	var res WikiCommitList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
