// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WikiPageMetaData WikiPageMetaData wiki page meta information
//
// swagger:model WikiPageMetaData
type WikiPageMetaData struct {

	// HTML URL
	HTMLURL string `json:"html_url,omitempty"`

	// sub URL
	SubURL string `json:"sub_url,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// last commit
	LastCommit *WikiCommit `json:"last_commit,omitempty"`
}

// Validate validates this wiki page meta data
func (m *WikiPageMetaData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLastCommit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiPageMetaData) validateLastCommit(formats strfmt.Registry) error {
	if swag.IsZero(m.LastCommit) { // not required
		return nil
	}

	if m.LastCommit != nil {
		if err := m.LastCommit.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("last_commit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("last_commit")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this wiki page meta data based on the context it is used
func (m *WikiPageMetaData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLastCommit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WikiPageMetaData) contextValidateLastCommit(ctx context.Context, formats strfmt.Registry) error {

	if m.LastCommit != nil {

		if swag.IsZero(m.LastCommit) { // not required
			return nil
		}

		if err := m.LastCommit.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("last_commit")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("last_commit")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WikiPageMetaData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WikiPageMetaData) UnmarshalBinary(b []byte) error {
	var res WikiPageMetaData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
