variables:
  - &golang_image 'golang:1.22'

when:
  - event: [push, pull_request, manual]

steps:
  - name: setup
    image: *golang_image
    environment:
      GOPROXY: "https://goproxy.io"
      GO111MODULE: "on"
      HTTP_PROXY: ""
      FORGEJO_SDK_TEST_URL: "http://forgejo:3000"
      FORGEJO_SDK_TEST_USERNAME: "test01"
      FORGEJO_SDK_TEST_PASSWORD: "test01"
    commands:
      - git checkout ${CI_COMMIT_SHA}
      - go version
      - make clean

  - name: vet
    image: *golang_image
    commands:
      - make vet

  - name: lint
    image: *golang_image
    commands:
      - make ci-lint
