variables:
  - &golang_image 'golang:1.22'

when:
  - branch: main
    event: push
    path:
      exclude: ['*.md', 'docs/**']
  - event: [pull_request]
    path:
      exclude: ['*.md', 'docs/**']

steps:
  - name: build
    image: *golang_image
    commands:
      - make build

depends_on:
  - lint