variables:
  - &golang_image 'golang:1.22'

when:
  - branch: main
    event: push
  - event: [pull_request, manual]

steps:
  - name: vendor
    image: *golang_image
    directory: forgejo
    commands:
      - go mod vendor

  - name: vet
    image: *golang_image
    depends_on: [vendor]
    commands:
      - make vet

  - name: lint
    image: *golang_image
    depends_on: [vendor]
    commands:
      - make ci-lint
