variables:
  - &golang_image 'golang:1.22'

when:
  - event: [push, pull_request, manual]

steps:
  - name: vendor
    image: *golang_image
    commands:
      - go mod vendor

  - name: vet
    image: *golang_image
    commands:
      - make vet

  - name: lint
    image: *golang_image
    commands:
      - make ci-lint
